const POST_LOGIN = 'titleParam/GET_LIST_TO_DO';
const GET_TOKEN_SUCCESS = 'titleParam/GET_TOKEN_SUCCESS';
const SHOW_ERROR = 'titleParam/SHOW_ERROR';

export { POST_LOGIN,GET_TOKEN_SUCCESS,SHOW_ERROR };