const GET_LIST_TO_DO = 'todo/GET_LIST_TO_DO';
const GET_LIST_TO_DO_SUCCESS = 'todo/GET_LIST_TO_DO_SUCCESS';
const DELETE_TO_DO = 'todo/DELETE_TO_DO';
const ADD_TO_DO = 'todo/ADD_TO_DO';
const SEARCH_TO_DO = 'todo/SEARCH_TO_DO';
const GET_LIST_SEARCH_TO_DO_SUCCESS = 'todo/GET_LIST_SEARCH_TO_DO_SUCCESS';

export { GET_LIST_TO_DO, DELETE_TO_DO, ADD_TO_DO, GET_LIST_TO_DO_SUCCESS, SEARCH_TO_DO, GET_LIST_SEARCH_TO_DO_SUCCESS };